---
- include_vars: secrets.yml

- name: Add wlan0 to /etc/network/interfaces
  blockinfile:
    path: /etc/network/interfaces
    block: |
      allow-hotplug wlan0
      iface wlan0 inet manual
          wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

- name: Generate encrypted passphrases WPA WPA2
  command: wpa_passphrase '{{ item.ssid }}' '{{ item.password }}'
  when: item.password is defined
  with_items: "{{ WIFI_CONFIG }}"
  register: ENCRYPTED_WIFI_PASSWORDS
  no_log: True

- name: Generate encrypted passphrases Enterprise
  shell: echo '{{ item.ssid }}' | echo -n '{{ item.password }}' | iconv -t utf16le | openssl md4
  # echo {{ item.ssid }} so that its saved in the var
  when: item.password is defined
  with_items: "{{ WIFI_CONFIG }}"
  register: ENCRYPTED_WIFI_ENTERPRISE_PASSWORDS
  no_log: True

- name: Create wpa_supplicant.conf
  template:
    src: wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0600

- name: Reload dhcpcd
  command: systemctl daemon-reload
