---
- name: Install apt_packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ apt_packages }}"

- name: Get git repo
  git:
    repo: "https://github.com/jgarff/rpi_ws281x.git"
    dest: /tmp
    
- name: Build the library
  command: python /tmp/rpi_ws281x/setup.py build

- name: Install the library
  command: python /tmp/rpi_ws281x/setup.py install
