---
- name: Install apt_packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ apt_packages }}"

- name: Get git repo
  git:
    repo: "https://github.com/jgarff/rpi_ws281x.git"
    dest: /tmp/rpi_ws281x
    
- name: Build the library
  command: python setup.py build
  args:
    chdir: /tmp/rpi_ws281x/python

- name: Install the library
  command: python setup.py install
  args:
    chdir: /tmp/rpi_ws281x/python
