---
- name: Install packages for apt over https
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add docker gpg key
  apt_key:
    url: https://yum.dockerproject.org/gpg
    state: present

- name: Add docker apt repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo/ raspbian-jessie main"
    state: present

- name: Install Docker
  apt:
    name: docker-engine
    state: present
    update_cache: yes

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add pi user to the docker group
  user:
    name: pi
    groups: docker
    append: yes

- name: Install pip
  easy_install:
    name: pip
    state: latest

- name: Install Docker-Compose
  pip:
    name: docker-compose
    state: present
