---
- hosts: all
  become: yes
  user: pi
  roles:
    - { role: wifi, tags: ['pi_setup', 'wifi'] }
    - { role: docker, tags: ['pi_setup', 'docker'] }
    - { role: neopixels, tags: ['code'] }
    - { role: nginx, tags: ['nginx']}
    - { role: ssh_setup, tags: ['pi_setup', 'ssh'] }
